### ISSUE TITLE
Add Record flow

### ISSUE THREAD

**Issue by lukecyca** [mycoralhealth/mycoral-patient#5]
Instruct the user to "Present this QR code to your medical lab so they can upload your results to the blockchain" and show the QR code.

Then below that a section called "Upload your own record" with a series of buttons:
* Take photo of medical record ➔ This goes to a page to upload a photo (or simulate it for now)
* Add _Basic Heart_ test results ➔ This goes to a page with a form for the corresponding fields for this record type. Ideally saving the form actually updates our mocked data, and the record appears on the "My Records" screen.
* Add _Genetic_ test results ➔ ditto

**Comment by grcevski** [comment]
I think I've got most of this already, except the photo upload. I just need to split it off that one screen where I currently shoved everything in.
