### ISSUE TITLE
Show version in app

### ISSUE THREAD

**Issue by lukecyca** [mycoralhealth/mycoral-patient#59]
It's hard to know what version is running. We should burn an identifier into each build.

We could use any available [env var from TravisCI](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables), such as `$TRAVIS_BRANCH:$TRAVIS_COMMIT ` or `$TRAVIS_BUILD_NUMBER`.

Then in a build script do something like:

```
echo "var version = '$TRAVIS_BRANCH:$TRAVIS_COMMIT';" > src/version.js
exp publish
```

Then from our app's settings screen (or some other spot out-of-the-way) we can import that variable and display the version.

**Comment by lukecyca** [comment]
This is mostly done in #62.

However the version.js is still static and will need to be bumped manually. It would be good to have it updated/enforced by the build system based on git tags/branches/commits.

**Comment by grcevski** [comment]
I agree completely, that was just the UI part :).

**Comment by lukecyca** [comment]
We should pull the version from the `app.json` instead, to avoid unnecessary duplication and confusion if they are out of sync.
